name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run coverage tests
        run: poetry run invoke coverage-report
      - name: Coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Run pylint tests
        run: poetry run invoke lint
      - name: Run Robot Framework
        run: poetry run invoke robot-test
